name: Integration Test for HA Minimal Deployment

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'

    steps:
      - name: Set env and tools
        run: |
          echo "TESTNAMESPACE=op-test-min-$(date +%s)" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          access_token_lifetime: 600s

      - name: Use the GKE Autopilot test cluster
        uses: 'google-github-actions/get-gke-credentials@v1.0.0'
        with:
          cluster_name: 'dev-integrationtesting'
          location: 'us-central1'

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Operator
        run: |
          for i in {1..3}; do
            kubectl cluster-info
            kubectl get pods -n kube-system
            echo "current-context:" $(kubectl config current-context)
            echo "environment-kubeconfig:" ${KUBECONFIG}
            kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
            if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
              echo "pubsubplus-eventbroker-operator is already deployed"
              break
            else
              kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
              make deploy | grep 'created \| configured'
              kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
              if [ $? -eq 0 ]; then
                break
              else
                echo "Rollout status check failed, retrying in 20 seconds..."
                sleep 20
              fi
            fi
          done

      - name: Testing the Operator - HA Minimal
        run: |
          for i in {1..3}; do
            kubectl create ns $TESTNAMESPACE; kubectl config set-context --current --namespace=$TESTNAMESPACE
            kubectl apply -f ci/manifests/eventbroker-ha-minimal.yaml | grep "test-ha-minimal created"
            sleep 10 ; kubectl get all
            kubectl wait pods --selector app.kubernetes.io/instance=test-ha-minimal --for condition=Ready --timeout=300s
            if [ $? -eq 0 ]; then
              break
            else
              echo "Waiting for pods failed, retrying in 5 seconds..."
              sleep 5
            fi
          done
          kubectl get po --show-labels -n $TESTNAMESPACE | grep test-ha-minimal | grep "1/1"
          kubectl get po --show-labels -n $TESTNAMESPACE | grep test-ha-minimal | grep active=true
          kubectl get sts -n $TESTNAMESPACE | grep test-ha-minimal
          kubectl port-forward svc/test-ha-minimal-pubsubplus -n $TESTNAMESPACE 55555:55555 &
          sleep 5
          curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
          tar -xvf SDKPERF_C_LINUX64
          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
          kubectl delete eventbroker test-ha-minimal -n $TESTNAMESPACE | grep deleted


      - name: Cleanup
        if: ${{ always() }}
        run: |
          kubectl delete pvc -n $TESTNAMESPACE --all --ignore-not-found
          kubectl delete ns $TESTNAMESPACE --ignore-not-found
