name: Integration Test for FULL HA Taints and Toleration Support

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'

    steps:
      - name: Set env and tools
        run: |
          echo "TESTNAMESPACE=op-test-full-$(date +%s)" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          access_token_lifetime: 600s

      - name: Use the GKE Autopilot test cluster
        uses: 'google-github-actions/get-gke-credentials@v1.0.0'
        with:
          cluster_name: 'dev-integrationtesting'
          location: 'us-central1'

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Operator
        run: |
          for i in {1..3}; do
            kubectl cluster-info
            kubectl get pods -n kube-system
            echo "current-context:" $(kubectl config current-context)
            echo "environment-kubeconfig:" ${KUBECONFIG}
            kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
            if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
              echo "pubsubplus-eventbroker-operator is already deployed"
              break
            else
              kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
              make deploy | grep 'created \| configured'
              kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
              if [ $? -eq 0 ]; then
                break
              else
                echo "Rollout status check failed, retrying in 20 seconds..."
                sleep 20
              fi
            fi
          done

      - name: Testing the Operator - HA Tolerations
        run: |
          kubectl create ns $TESTNAMESPACE; kubectl config set-context --current --namespace=$TESTNAMESPACE
          #create taint for first node
          nodesAll=$(kubectl get nodes --output name) &&  firstNode=`echo "${nodesAll}" | head -1`
          kubectl taint nodes $firstNode node=primary:NoSchedule
          kubectl taint nodes $firstNode node=backup:NoSchedule
          kubectl taint nodes $firstNode node=monitor:NoSchedule
          #confirm node taint
          echo "$firstNode has been tainted"
          kubectl describe $firstNode
          kubectl apply -f ci/manifests/eventbroker-ha-taints.yaml | grep "ha-toleration-test created"
          sleep 10 ; kubectl get all
          kubectl wait pods --selector app.kubernetes.io/instance=test-ha --for condition=Ready --timeout=300s
          kubectl get po --show-labels -n $TESTNAMESPACE | grep test-ha | grep "1/1"
          kubectl get po --show-labels -n $TESTNAMESPACE | grep test-ha | grep active=true
          kubectl get sts ha-toleration-test-pubsubplus-p -o jsonpath='{.spec.template.spec.tolerations}' | grep "value":"primary"
          kubectl get sts ha-toleration-test-pubsubplus-b -o jsonpath='{.spec.template.spec.tolerations}' | grep "value":"backup"
          kubectl get sts ha-toleration-test-pubsubplus-m -o jsonpath='{.spec.template.spec.tolerations}' | grep "value":"monitor"        
          kubectl delete eventbroker test-ha -n $TESTNAMESPACE | grep deleted
          kubectl taint nodes $firstNode node=primary:NoSchedule-
          kubectl taint nodes $firstNode node=backup:NoSchedule-
          kubectl taint nodes $firstNode node=monitor:NoSchedule-
          kubectl get nodes -o wide

      - name: Cleanup
        if: ${{ always() }}
        run: |
          kubectl delete pvc -n $TESTNAMESPACE --all --ignore-not-found
          kubectl delete ns $TESTNAMESPACE --ignore-not-found
