name: Integration Test for FULL HA Deployment

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'read'

    steps:
      - name: Set env and tools
        run: |
          echo "TESTNAMESPACE=op-test-full-$(date +%s)" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.0.0'
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          access_token_lifetime: 600s

      - name: Use the GKE Autopilot test cluster
        uses: 'google-github-actions/get-gke-credentials@v1.0.0'
        with:
          cluster_name: 'dev-integrationtesting'
          location: 'us-central1'

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Operator
        run: |
          sleep 20;
          for i in {1..3}; do
            kubectl cluster-info
            kubectl get pods -n kube-system
            echo "current-context:" $(kubectl config current-context)
            echo "environment-kubeconfig:" ${KUBECONFIG}
            kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
            if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
              echo "pubsubplus-eventbroker-operator is already deployed"
              break
            else
              kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
              make deploy | grep 'created \| configured'
              kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
              if [ $? -eq 0 ]; then
                break
              else
                echo "Rollout status check failed, retrying in 20 seconds..."
                sleep 20
              fi
            fi
          done

      - name: Testing the Operator - HA
        run: |
          kubectl create ns $TESTNAMESPACE; kubectl config set-context --current --namespace=$TESTNAMESPACE
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=*"
          kubectl create secret tls test-tls --key="tls.key" --cert="tls.crt"
          openssl x509 -in tls.crt -out tls.public.pem
          openssl rsa -in tls.key -text > tls.private.pem
          kubectl create secret tls monitoring-tls --key="tls.private.pem" --cert="tls.public.pem"
          kubectl apply -f ci/manifests/eventbroker-ha.yaml | grep "test-ha created"
          sleep 10 ; kubectl get all
          kubectl wait pods --selector app.kubernetes.io/instance=test-ha --for condition=Ready --timeout=300s
          kubectl get po --show-labels -n $TESTNAMESPACE | grep test-ha | grep "1/1"
          kubectl get po --show-labels -n $TESTNAMESPACE | grep test-ha | grep active=true
          kubectl get po -n $TESTNAMESPACE -o jsonpath='{.items[0].metadata.name}' | xargs -I {} kubectl get po {} -n $TESTNAMESPACE -o jsonpath='{.spec.containers[0].securityContext.seLinuxOptions}' | grep "system_u"
          kubectl get sts -n $TESTNAMESPACE | grep test-ha
          kubectl port-forward svc/test-ha-pubsubplus -n $TESTNAMESPACE 55555:55555 &
          sleep 5
          curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
          tar -xvf SDKPERF_C_LINUX64
          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
          kubectl delete eventbroker test-ha -n $TESTNAMESPACE | grep deleted

      - name: Cleanup
        if: ${{ always() }}
        run: |
          kubectl delete pvc -n $TESTNAMESPACE --all --ignore-not-found
          kubectl delete ns $TESTNAMESPACE --ignore-not-found
